FROM node:7
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app
CMD node server.js
AWS CLOUD COMPUTING STEPS


Sudo yum install git
Git clone url
Ls
Cd
Ls
Cd
Sudo yum install docker
Sudo systemctl start docker
Sudo systemctl enable docker
Sudo systemctl status docker
Sudo docker build -t nodeapp .
Sudo docker run -d -p 8081:8081 nodeapp
Sudo docker ps


For inbuild images libraries

Sudo docker images
Sudo docker pull hello-world
Repeat from build
push

push

#For adding file to git#
git add .
git commit -m "message"
git status 
git push
